### PR TITLE
add imported target if TinyXML2 was found by FastRTPS

### LINKED ISSUE #429: failing to build rosbag2_tests
When only FastRTPS is selected: [Build Status](https://ci.ros2.org/job/ci_windows/10888/)

### LINKED ISSUE #927: can't find tinyxml2::tinyxml2
## Bug report

**Required Info:**

Packages (indirectly) depending on `tinyxml2` might fail, because the taget `tinyxm2::tinyxml2` is not found. 
```
02:59:47 CMake Error at CMakeLists.txt:35 (add_library):
02:59:47   Target "rosbag2_transport" links to target "tinyxml2::tinyxml2" but the
02:59:47   target was not found.  Perhaps a find_package() call is missing for an
02:59:47   IMPORTED target, or an ALIAS target is missing?
```

This happened at `rviz_common` as well as `rosbag2_transport` and is heavily depend on the include order of packages - the order in which `find_package` is called.

See the example of rviz common here: https://github.com/ros2/rviz/pull/542/commits/b327b438aefec3b5ccd6142e1ab255de19d14be4

- Operating System:
  - Windows 10
- Installation type:
  - Source, partially provoked by building with `-DENABLE_TESTING=OFF`

#### Steps to reproduce issue

Revert the commit in here: https://github.com/ros2/rviz/pull/542/commits/b327b438aefec3b5ccd6142e1ab255de19d14be4 

or look at the current Windows packaging job: https://ci.ros2.org/view/packaging/job/packaging_windows/1752/console#console-section-20

Note that for the latter, the packaging job fails because `ENABLE_TESTING=OFF`, whereas the build succeeds if tests are built.

#### Expected behavior

The order in which `find_package` doesn't matter, meaning packages can be sorted alphabetically.

#### Actual behavior

The order _does_ matter! In the example of `tinyxml2`, whenever being `find_package`'d first, the compilation goes through smoothly. Being find first, also implies being found via `find_package(pluginlib)` or any other package exporting the dependency of `tinyxml2`.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes ros2/rosbag2#429, fixes ros2/ros2#927.

[Build Status](https://ci.ros2.org/job/ci_windows/10912/)

Full CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10992/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6328/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8952/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10913/)

### CODE REVIEW

**Review by Karsten1987 — APPROVED** [review]
Thanks for coming up with a solution. I am hopeful that this will solve the problem we encountered with the include order of `find_package`. 

Two questions though:

* Would it make sense to add this logic before adding the `FindTinyXML2.cmake` onto the `CMAKE_MODULE_PATH` to make sure that only the existing logic for finding tinyxml2 is being used? Basically saying to put the existing line `list(INSERT ....)` in an `else` clause, if tinyxml2 is not found yet.
* I know it's two different cmake files, but can the logic be de-duplicated? I'd prefer to maintain that custom cmake logic only in one place.

**Review by jacobperron — APPROVED** [review]

**Comment by dirk-thomas** [comment]
> Two questions though:

I would consider both for a follow up PR in order to get this fix merged asap.

**Comment by Karsten1987** [comment]
fine by me.

**Review by wjwwood — APPROVED** [review]
looks reasonable to me

**Pull request merged**
